import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Play } from "lucide-react";
import { BorderTrailCard } from "./core/BorderTrailCard";

function VideoThumbnail({ onClick }) {
  return (
    <div 
      className="absolute inset-0 z-10 flex items-center justify-center cursor-pointer overflow-hidden group bg-[#08130e]"
      onClick={onClick}
    >
      {/* High-End Tech Gradient Background */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#134226] via-[#08130e] to-[#030604] opacity-90" />
      
      {/* Brand Text Watermark mimicing the provided mockup exactly */}
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-40 transition-opacity duration-700 group-hover:opacity-20 scale-95 group-hover:scale-100 transition-transform">
         <span className="text-4xl md:text-7xl font-blocky font-bold tracking-[0.2em] text-white/90">
            QUICK<span className="text-[#2ebd68]">LEARN.AI</span>
         </span>
      </div>

      {/* Premium Play Button */}
      <div className="relative flex items-center justify-center">
        {/* Pulsing Concentric Rings - Elegant green */}
        <motion.div
          className="absolute inset-0 rounded-full border border-[#2ebd68]/60"
          animate={{ scale: [1, 1.8], opacity: [0.8, 0] }}
          transition={{ duration: 1.5, repeat: Infinity, ease: "easeOut" }}
        />
        <motion.div
          className="absolute inset-0 rounded-full border border-[#2ebd68]/30"
          animate={{ scale: [1, 2.5], opacity: [0.5, 0] }}
          transition={{ duration: 1.5, delay: 0.3, repeat: Infinity, ease: "easeOut" }}
        />
        
        {/* Solid Center */}
        <div className="w-16 h-16 md:w-20 md:h-20 bg-white rounded-full flex items-center justify-center shadow-[0_0_40px_rgba(46,189,104,0.3)] relative z-10 transition-transform duration-300 group-hover:scale-110">
          <Play className="w-8 h-8 md:w-10 md:h-10 text-[#1a6b3c] fill-[#1a6b3c] ml-1" />
        </div>
      </div>
    </div>
  );
}

function Hero() {
  const [isPlaying, setIsPlaying] = useState(false);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.08,
        delayChildren: 0.1
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 15 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { type: "spring", stiffness: 100, damping: 20 },
    },
  };

  return (
    <section className="relative w-full min-h-[100dvh] bg-[var(--background)] overflow-hidden flex flex-col pt-24 md:pt-32">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,700;1,700&display=swap');
        
        .font-blocky {
          font-family: 'Chakra Petch', sans-serif;
          text-transform: uppercase;
        }
        .graph-paper-bg {
          background-image: 
            linear-gradient(to right, rgba(0,0,0,0.03) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(0,0,0,0.03) 1px, transparent 1px);
          background-size: 40px 40px;
        }
        .dark .graph-paper-bg {
          background-image: 
            linear-gradient(to right, rgba(255,255,255,0.03) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(255,255,255,0.03) 1px, transparent 1px);
        }
      `}</style>
      
      {/* Background Texture */}
      <div className="absolute inset-0 graph-paper-bg pointer-events-none" />
      {/* Subtle fade at the bottom of the background */}
      <div className="absolute bottom-0 left-0 right-0 h-48 bg-gradient-to-t from-[var(--background)] to-transparent pointer-events-none z-10" />

      {/* Main Content Area */}
      <div className="relative z-20 flex flex-col items-center text-center px-6 max-w-5xl mx-auto flex-1">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="flex flex-col items-center w-full"
        >
          {/* Badge */}
          <motion.div variants={itemVariants} className="mb-8 md:mb-10 mt-4">
            <span className="inline-block py-1.5 px-4 rounded-full border border-[var(--border)] bg-[var(--surface-container-low)]/50 backdrop-blur-sm text-[10px] md:text-xs font-bold tracking-[0.2em] uppercase text-[#1a6b3c] dark:text-[#2ebd68] shadow-sm">
              Generated by students for students.
            </span>
          </motion.div>

          {/* Headline - Elegant Dark Green */}
          <motion.h1 
            className="flex flex-col items-center justify-center w-full mb-8 text-balance relative"
          >
            <motion.span variants={itemVariants} className="font-blocky text-6xl md:text-8xl lg:text-[7.5rem] text-[var(--foreground)] tracking-tight leading-[0.9] z-10 text-center">
              Exams are a<br className="hidden md:block" /> nightmare
            </motion.span>
            <motion.span variants={itemVariants} className="font-blocky italic text-[#1a6b3c] dark:text-[#2ebd68] text-5xl md:text-7xl lg:text-[6.5rem] mt-2 md:mt-4 z-20 select-none text-center">
              NOT ANYMORE
            </motion.span>
          </motion.h1>

          {/* Subheading */}
          <motion.p variants={itemVariants} className="text-base md:text-lg text-[var(--text-muted)] max-w-2xl font-medium leading-relaxed mb-10 text-balance z-10">
            Replace scattered notes, endless PDFs, and frantic quizzes with one elegant, AI-powered study journal.
          </motion.p>

          {/* CTAs - Classy Brand Green */}
          <motion.div variants={itemVariants} className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto z-10">
            <Link 
              to="/quiz"
              className="group flex items-center justify-center gap-2 bg-[#1a6b3c] hover:bg-[#13522d] text-white px-8 py-3.5 rounded-full font-bold tracking-wide uppercase text-sm transition-all duration-200 w-full sm:w-auto shadow-[0_4px_20px_rgba(26,107,60,0.2)] hover:shadow-[0_4px_25px_rgba(26,107,60,0.3)]"
            >
              Start learning free
              <div className="flex items-center justify-center rounded-full bg-white/20 p-1 group-hover:translate-x-1 transition-transform duration-300">
                <ArrowRight className="w-4 h-4 ml-0.5 text-white" />
              </div>
            </Link>
            
            <button 
              onClick={() => setIsPlaying(true)}
              className="flex items-center justify-center gap-2 border-2 border-[var(--border)] bg-[var(--surface-container-lowest)] hover:bg-[var(--surface-variant)] text-[var(--foreground)] px-8 py-3.5 rounded-full font-bold tracking-wide uppercase text-sm transition-all duration-200 w-full sm:w-auto"
            >
              <Play className="w-4 h-4 text-[#1a6b3c] dark:text-[#2ebd68] fill-current" />
              Watch Demo
            </button>
          </motion.div>
        </motion.div>
      </div>

      {/* Video Preview Card */}
      <div className="relative z-20 w-full max-w-5xl mx-auto px-4 mt-16 md:mt-24 mb-24">
        <motion.div
           initial={{ opacity: 0, y: 150 }}
           animate={{ opacity: 1, y: 0 }}
           transition={{ type: "spring", stiffness: 60, damping: 20, delay: 0.5 }}
        >
          <BorderTrailCard 
            className="w-full bg-[#050505] rounded-[1.5rem] md:rounded-[2rem] border border-white/10 shadow-2xl overflow-hidden flex flex-col p-0.5 sm:p-1"
            size={180}
            transition={{
              repeat: Infinity,
              duration: 10,
              ease: 'linear',
            }}
          >
            <div className="w-full h-full bg-[#050505] rounded-[calc(1.5rem-0.125rem)] md:rounded-[calc(2rem-0.25rem)] overflow-hidden">
              
              {/* Media UI Topbar */}
              <div className="w-full flex items-center justify-between px-6 py-3 border-b border-white/5 bg-white/[0.02]">
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-white/20" />
                  <div className="w-3 h-3 rounded-full bg-white/20" />
                  <div className="w-3 h-3 rounded-full bg-white/20" />
                </div>
                <div className="text-xs font-bold text-white/40 tracking-[0.1em] font-blocky uppercase">quicklearn.ai/study</div>
                <div className="w-8" />
              </div>

              {/* Video Player Box */}
              <div className="w-full aspect-video bg-black relative overflow-hidden group">
                <iframe
                  className="absolute inset-0 w-full h-full"
                  src={`https://www.youtube.com/embed/Ui-Qv5YKu-0?${isPlaying ? 'autoplay=1&' : ''}rel=0&modestbranding=1`}
                  title="QuickLearn AI"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowFullScreen
                ></iframe>

                {!isPlaying && <VideoThumbnail onClick={() => setIsPlaying(true)} />}
              </div>
            </div>
          </BorderTrailCard>
        </motion.div>
      </div>
    </section>
  );
}

export default Hero;
